name: Snyk
on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: 0 8,16 * * *

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Snyk Vulnerability Check
        uses: snyk/actions/gradle-jdk17@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}