language: java

jdk:
- oraclejdk8

sudo: false

services:
- rabbitmq

before_install:
- chmod +x gradlew

notifications:
  email: false

addons:
  sonarcloud:
    organization: gessnerfl-github
    token:
      secure: fFLE4NbifJlA+AyEIzdkGeZu2/RA/D8VfxSELnbaTwG1BpBKkOb7+rTegqM4OGVTNTsAC3TR6Dn4NI3/CGWgyFiJANHLqV/lZP8zDvXDXtjUyVZP3XyBspKFYwbt+g+vZ5w7CTPQ0efsI0wKaaU1I4UW3yAnRBnVvF2V4cIA0etE3Kr3ceWBEJhBrlwGlPS4bmmbpx6JqN+ldrGgQXvktWsTlYdci1/lymM1mbGydacj8xf7ZMafGWkih6nwNS4Xbl4GBYohXz98s375VdeJcy2R5k1PGb6xr2vQWzJh+35DHRAOXmC5yQ9YmL2juLT9jPlBx/TX4fHOXZt3fFPg1xbfw+uuwJka99oYM+6TVPIFLFVzWZnuSyoTz8EqqDDlcWeGOn0tTYiXyjuqnVeoCndqN5c9Lmj5l3BACQq2El3P1WfqZlxtj7KbiOjRHL1zOuYF4nebs3vhDG/G4at3J77g/gHjiYS78b1KLonwJwA391CKRkoUGbcZoSc4Th54NgcjhzMmDSEXl948UnYmZTEMVc6r7q5ymrVY34rhS4XxpPdKeTqp8wghq2a6JTrl61hk1cb7GIB6S+9u0rNZVHATJXrkQycFMrl+6Yy2x96Dxs0QFrqQjWktchL3jshOZxxWyqaBo6fjuty5NYlpYSxYy29mGxSks+4DdgvjODk=

script:
- "./gradlew build sonarqube"

deploy:
  provider: releases
  api_key:
    secure: k24fbqPys7C6h7hTmEZG61oOYFNrf77/XczmOuolnvWMFxNRh1cgWTC7PkiFbqa2LyDkThLKkXPO/VfSloI4hs/9ygVh6iV6BIbt5bz9QviAJaxHaYAEAur8xhCHfbt8JCXAzMewKna7wx97t5v8JNCEKGZXVBuw+4J96gqxu8dW4lCYqeEJtZ0/xkzze/qxdawdYjc3TReF9yOz1qWXytscpyUVH3Rq9hdrSoQCdxF3qXw/qHdgDOIl6offm9b4ME1EPgZoBejAmfxsZm2XTLS0HXoQquWgm/XxirT3NkO420aJWDw8tqJn7CjZ1zry7uvEtBNR0zsmNW67z1yvQTtKlHBGID0K9ukNHduD+kwqa5g8xg7LGVG6HzVHFupGjKYmNbChJFlDhhEwH9poRwIjoYgOgyttRn0ykbwXKI3MuC+IAxF6VMMkR5qdw3qnGNJehr3H6dQzpwxcKCoUHePtUJUK6XN3mcDP54Knxa3hGipxEaUzpbI8dVYFXdYBz8asX8FhA8KKQ7DsSodY4KmQXkGRcFkvktiXLan/GKsUxDsKvYRHQgIPymQMMACdU4vybjFIW4cP9mnkwd63rvkJKOS6QZrwpMUrNSHmnblooJ5/t/Pl9HjLYxyv5TGQZD+vYKeKsPNgxCyAjXSQukDVuoZnbsXOxhZPeycL/9A=
  file: build/libs/rabbitmq-queue-management-$TRAVIS_TAG.jar
  skip_cleanup: true
  on:
    tags: true