language: java

jdk:
- oraclejdk8

sudo: false

services:
- rabbitmq

before_install:
- chmod +x gradlew

notifications:
  email: false

addons:
  sonarcloud:
    organization: "gessnerfl-github"
    token:
      secure: "fFLE4NbifJlA+AyEIzdkGeZu2/RA/D8VfxSELnbaTwG1BpBKkOb7+rTegqM4OGVTNTsAC3TR6Dn4NI3/CGWgyFiJANHLqV/lZP8zDvXDXtjUyVZP3XyBspKFYwbt+g+vZ5w7CTPQ0efsI0wKaaU1I4UW3yAnRBnVvF2V4cIA0etE3Kr3ceWBEJhBrlwGlPS4bmmbpx6JqN+ldrGgQXvktWsTlYdci1/lymM1mbGydacj8xf7ZMafGWkih6nwNS4Xbl4GBYohXz98s375VdeJcy2R5k1PGb6xr2vQWzJh+35DHRAOXmC5yQ9YmL2juLT9jPlBx/TX4fHOXZt3fFPg1xbfw+uuwJka99oYM+6TVPIFLFVzWZnuSyoTz8EqqDDlcWeGOn0tTYiXyjuqnVeoCndqN5c9Lmj5l3BACQq2El3P1WfqZlxtj7KbiOjRHL1zOuYF4nebs3vhDG/G4at3J77g/gHjiYS78b1KLonwJwA391CKRkoUGbcZoSc4Th54NgcjhzMmDSEXl948UnYmZTEMVc6r7q5ymrVY34rhS4XxpPdKeTqp8wghq2a6JTrl61hk1cb7GIB6S+9u0rNZVHATJXrkQycFMrl+6Yy2x96Dxs0QFrqQjWktchL3jshOZxxWyqaBo6fjuty5NYlpYSxYy29mGxSks+4DdgvjODk="

script:
  - ./gradlew build sonarqube

deploy:
  provider: releases
  api_key:
    secure: SWblzz9vIOgEzcl4FxNCvEaKeuZOP5SdmUM2gJmuWPIDfBxX6vp8gj4KxBHazKpzGpdyzQ20sobSryRzC/4mnno7tJL39ziSuPhI647DVikeT3y4pV6+Yv/9sF68dgcOEh9plI126Eq1YDZ3b6urPUidvx3/rbp4LrXHkn9Uvpz9TJHdF7nwWWG+OXF1QhW0V49LLjgJbyVaiZw/LFo1DR5H3rDfgschf6P/hPzDDR5orZjyVFwykQ815QrWccTszKUuwcntxhgXACbCzfhWm7qM6pfy0J3APiohwpS2X+mbGTbzlU7DGB7EPfWuUyhHquHPO82GKSAJICw0qA214cksS4cclbygahWM88+ZE6FJ5FtX/h6iVWse4btG3+1WBCK1bLlzlLaIseArQNy2TT3Kt8lk8eRcQR2WUVI2qgnkk19VeuwJKk2OajGZOL5dvAgIrP6lvUYR2Lsdgdkxf9RUHSy2fe33yfkJBL/W8foK0pFDPWdE91sGVUY+4pPVFWTx3cLAfvZC+y/rlPePjDv53pkPHEwITurthZq/OU1pU1x3ahxpfHw9OM70uwTS2S56g+KcGmpLEDG5lOgSAWuRkAV1nq+zR10BesfSeQu0r5JtScbKZ1pTP0CX1AiW8jXrzaQ+6/fLH/TJZrnSZJBdD0/P81VTjox6CaKi2Dk=
  file: build/libs/rabbitmq-queue-management-$TRAVIS_TAG.jar
  on:
    tags: true
