version: '2.2'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  openldap:
    image: osixia/openldap:1.4.0
    container_name: openldap
    hostname: openldap
    ports:
      - 389:389
      - 636:636
    environment:
      LDAP_ORGANISATION: "gessnerfl"
      LDAP_DOMAIN: "gessnerfl.de"
      LDAP_ADMIN_PASSWORD: "Test1234"
    volumes:
      - ./src/test/resources/test-users.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/test-users.ldif
    command: "--copy-service"