spring:
  application:
    name: RabbitMQ Queue Managment

server:
  port: 8780
management:
  server:
    port: 8781
  health:
    ldap:
      enabled: false

de:
  gessnerfl:
    rabbitmq:
      hostname: localhost
      port: 5672
      managementPort: 15672
      username: guest
      password: guest

#    security:
#      authentication:
#        enabled: true
#        ldap:
#          user-search-base: ou=people
#          user-search-filter: (uid={0})
#          group-search-base: ou=groups
#          group-search-filter: member={0}
#          context-source:
#            manager-dn: cn=admin,dc=gessnerfl,dc=de
#            manager-password: Test1234
#            root: dc=gessnerfl,dc=de
#            port: 389
#            url: ldap://localhost:389/dc=gessnerfl,dc=de
#        jwt:
#          token:
#            signingKey: bM95WuJZz49AZcJ3BT3qzZ8vJUvepWwZyVuFyYTj9GUrzXgGevVqYFMFVHyR3kyP